### ISSUE TITLE
Two files missing from Pro distribution break build... not found in original download

### ISSUE THREAD

**Issue by rwdim** [creativetimofficial/ct-now-ui-kit-pro#1]
fonts/nucleo-outline.svg (ref'd in _nucleo-outline.scss)
img/ink.png (ref'd in _plugin-isometricGrids.scss)

**Comment by tutNichts** [comment]
same here

**Comment by alexandru-paduraru** [comment]
@tutNichts and @rwdim thank you for using our product. The isometricGrids.scss is an old plugin that was removed from v1.0.1 but it seems we didn't remove it completely from SCSS so you can remove from line 25 in `assets/sass/now-ui-kit.scss`. For the font, we stopped using the svg because it is better for browser compatibilities to use the fonts (otf, ttf, woff etc.) si you can safely remove the line with the SVG from 16 in `assets/sass/now-ui-kit/_nucleo-outline.scss`. 

We will do this changes for the next version too.

Best,
Alex

**Comment by dbize** [comment]
Same issue here. Waiting next version with the fixed.
